#include "main.h"

// ============================================================================
// Setup (runs on Core 1)
// ============================================================================
void setup()
{
    Serial1.begin(115200, SERIAL_8N1, PIN_SERIAL1_RX, PIN_SERIAL1_TX);

    DynamicJsonDocument doc(1024);
    uint64_t bigTest = 0xFF34567890ABCDEF;
    uint32_t test = 0xFF345678;
    doc["bit_int"] = test;
    doc["real_big_int"] = bigTest;
    serializeJson(doc, Serial1);
    Serial1.println();

    // Configure power manager
    powerManager.setSleepDuration(5);
    powerManager.setWakeTimeout(5000);
    powerManager.setStorage(&storage);
    powerManager.markPreTxStart();
    
    Serial1.println("\n========================================");
    Serial1.println("RAK3112 ResonantLRRadio Demo");
    Serial1.println("Core 0 Radio Execution + AES-128-GCM");
    Serial1.println("========================================");

    // Initialize non-volatile storage (must be early to detect first boot)
    if (!storage.begin("resonant")) {
        Serial1.println("WARNING: Storage initialization failed!");
    }

    // Clear adoption on any reset that isn't a deep-sleep wake.
    // This lets the RST button (or power cycle) force re-adoption for testing,
    // while normal sleep/wake cycles preserve the adopted state.
    esp_reset_reason_t resetReason = esp_reset_reason();
    Serial1.print("Reset reason: ");
    Serial1.println(resetReason);

    if (resetReason != ESP_RST_DEEPSLEEP && storage.isAdopted()) {
        storage.clearParentId();
        Serial1.println("Non-sleep reset detected -- adoption cleared for re-adoption");
    }

    // Initialize encryption (mock mode uses mbedTLS, no ATECC608B needed)
    if (!encryption.begin()) {
        Serial1.println("WARNING: Encryption initialization failed!");
    } else {
        Serial1.println("Encryption initialized (mock mode)");

        // Load provisioned device credentials (private key + CA-signed cert)
        // to replace the random ephemeral keypair generated by begin().
        if (device_key_der_len > 0 && device_cert_der_len > 0) {
            Serial1.printf("Loading credentials: key=%u bytes (0x%02X 0x%02X), cert=%u bytes\n",
                device_key_der_len, device_key_der[0], device_key_der[1], device_cert_der_len);
            if (encryption.loadDeviceCredentials(device_key_der, device_key_der_len,
                                                  device_cert_der, device_cert_der_len)) {
                Serial1.println("Provisioned device credentials loaded");
            } else {
                Serial1.println("WARNING: Device credential loading failed, using ephemeral keys");
            }
        } else {
            Serial1.println("No device credentials provisioned, using ephemeral self-signed keys");
        }

        // Load the Resonant Root CA for mutual attestation during adoption.
        // The gateway's DER cert is verified against this CA chain.
        if (resonant_ca_cert_der_len > 0) {
            if (encryption.loadCACertBundle(resonant_ca_cert_der, resonant_ca_cert_der_len)) {
                Serial1.println("Root CA certificate loaded");
            } else {
                Serial1.println("WARNING: Root CA certificate failed to load");
            }
        } else {
            Serial1.println("WARNING: No Root CA provisioned -- mutual attestation disabled");
        }

        // For testing without a real adoption handshake, load a fixed session key
        // so both device and test gateway can encrypt/decrypt immediately.
        // In production this key is derived via ECDH + HKDF during adoption.
        if (!storage.isAdopted()) {
            uint8_t testKey[ResonantEncryption::AES128_KEY_SIZE] = {
                0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
                0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F
            };
            encryption.storeKey(testKey, sizeof(testKey),
                                ResonantEncryption::SLOT_SESSION_KEY);
            memset(testKey, 0, sizeof(testKey));
            Serial1.println("Test session key loaded for unadopted testing");
        }
    }

    firstBoot = resetReason == ESP_RST_POWERON;
    
    if (firstBoot) {
        Serial1.println(">>> FIRST BOOT - Metrics packet required <<<");
    } else {
        Serial1.printf("Boot #%u - Normal operation\n", storage.getBootCount());
    }

    // Create radio task on CORE 0 - radio init happens there
    xTaskCreatePinnedToCore(backgroundTasks, "RadioTask", 20000, NULL, 1, &backgroundTask, 0);
    Serial1.println("Waiting for radio initialization on Core 0...");

    while (!resonantRadio.radioInitialized && !powerManager.checkWakeTimeout()) {
        delay(10);
    }
    if(!resonantRadio.radioInitialized || millis() > powerManager.getWakeTimeout()) {
        Serial1.println("Radio initialization failed on Core 0, going to sleep");
        resonantRadio.deepSleep();
        powerManager.goToSleep();
    }else{
        Serial1.println("Radio initialized successfully on Core 0");
    }

    resonantRadio.onRxComplete(onDataReceived);
    resonantRadio.onTxComplete(onTxComplete);
    resonantRadio.onError(onRadioError);
    resonantRadio.setPowerManager(&powerManager);
    Serial1.println("Callbacks registered");

    RadioConfig currentConfig = resonantRadio.getConfig();
    Serial1.printf("Frequency: %.1f MHz\n", (double)(currentConfig.frequency / 1000000.0));
    if (currentConfig.modem == MODEM_LORA_MODE) {
        Serial1.printf("Mode: LoRa SF%d BW%d\n", 
            currentConfig.loraSpreadingFactor,
            currentConfig.loraBandwidth == 0 ? 125 : (currentConfig.loraBandwidth == 1 ? 250 : 500));
    } else {
        Serial1.printf("Mode: FSK %d bps\n", currentConfig.fskDatarate);
    }

    // Adoption-aware startup: check if device has a parent modem
    if (!storage.isAdopted()) {
        Serial1.println("\n--- Device NOT adopted - sending adoption advertise ---");
        sendAdoptionAdvertise();
    } else {
        uint8_t parentId[4];
        storage.getParentId(parentId);
        Serial1.printf("\n--- Device adopted by %02X:%02X:%02X:%02X ---\n",
            parentId[0], parentId[1], parentId[2], parentId[3]);
        
        if (multiPacketDemo) {
            Serial1.println("--- Multi-Packet Encrypted Telemetry ---");

            uint8_t* encPayload = nullptr;
            size_t encLen = 0;
            if (encryptPayload((const uint8_t*)genesis, strlen(genesis),
                               resonantFrame.telemetryFrameType,
                               &encPayload, &encLen)) {
                Serial1.printf("Sending %zu encrypted bytes (%d plaintext)\n",
                               encLen, strlen(genesis));
                currentTxContext = TxContext::TELEMETRY;
                resonantRadio.send(encPayload, encLen, parentId, telemetryAckRequired);
                delete[] encPayload;
            } else {
                Serial1.println("Encryption failed, sending plaintext fallback");
                currentTxContext = TxContext::TELEMETRY;
                resonantRadio.send((uint8_t*)genesis, strlen(genesis), parentId, telemetryAckRequired);
            }
        } else {
            Serial1.println("--- Single-Packet Encrypted Telemetry ---");
            uint8_t data[200];
            for (int i = 0; i < 200; i++) {
                data[i] = (uint8_t)i;
            }

            uint8_t* encPayload = nullptr;
            size_t encLen = 0;
            if (encryptPayload(data, 200,
                               resonantFrame.telemetryFrameType,
                               &encPayload, &encLen)) {
                uint8_t opts = ResonantFrame::buildOptionsV1(telemetryAckRequired);
                FrameData telemetryFrame = resonantFrame.buildTelemetryFrame(
                    encPayload, encLen, parentId, opts, txSequenceNumber);
                txSequenceNumber++;
                Serial1.printf("Transmitting encrypted telemetry frame: %zu bytes\n",
                               telemetryFrame.size);
                currentTxContext = TxContext::TELEMETRY;
                resonantRadio.send(telemetryFrame.frame, telemetryFrame.size);
                delete[] telemetryFrame.frame;
                delete[] encPayload;
            } else {
                Serial1.println("Encryption failed, sending plaintext fallback");
                uint8_t opts = ResonantFrame::buildOptionsV1(telemetryAckRequired);
                FrameData telemetryFrame = resonantFrame.buildTelemetryFrame(
                    data, 200, parentId, opts, txSequenceNumber);
                txSequenceNumber++;
                currentTxContext = TxContext::TELEMETRY;
                resonantRadio.send(telemetryFrame.frame, telemetryFrame.size);
                delete[] telemetryFrame.frame;
            }
        }
        Serial1.println("Transmission request queued...");
    }
}

// ============================================================================
// Loop (runs on Core 1 - radio handling is on Core 0)
// ============================================================================
void loop()
{    
    // Check for wake timeout (single packet mode only)
    if (!multiPacketDemo && powerManager.checkWakeTimeout()) {
        Serial1.println("Wake timeout reached");
    }

    // Check if we should sleep
    if (powerManager.shouldSleep() && resonantRadio.isTransmissionComplete()) {
        // Clear metrics pending flag before sleep (if it was first boot)
        if (firstBoot) {
            storage.updateLastMetricsTime();
        }
        resonantRadio.deepSleep();
        powerManager.goToSleep();
    }
}

// ============================================================================
// Command Processing
// ============================================================================
void handleCommand(uint8_t commandId, uint8_t* params, size_t paramsLength, uint8_t sourceID[4])
{
    uint8_t responseCode = ResonantFrame::CMD_RESPONSE_SUCCESS;
    
    Serial1.printf("Processing command: 0x%02X\n", commandId);
    
    switch (commandId) {
        case ResonantFrame::CMD_RESET_ENERGY:
            storage.resetEnergy();
            energyBuffer = 0.0f;
            Serial1.println("Command: Energy counter reset executed");
            break;
            
        case ResonantFrame::CMD_FACTORY_RESET:
            storage.factoryReset();
            energyBuffer = 0.0f;
            Serial1.println("Command: Factory reset executed");
            break;
            
        default:
            responseCode = ResonantFrame::CMD_RESPONSE_UNKNOWN_CMD;
            Serial1.printf("Unknown command: 0x%02X\n", commandId);
            break;
    }
    
    delay(150);
    
    // Encrypt the command response
    uint8_t responseData[2] = {commandId, responseCode};
    uint8_t* encPayload = nullptr;
    size_t encLen = 0;

    uint8_t cmdOpts = ResonantFrame::buildOptionsV1(false);
    if (encryption.isInitialized() &&
        encryptPayload(responseData, 2,
                       resonantFrame.commandResponseFrameType,
                       &encPayload, &encLen)) {
        FrameData response = resonantFrame.buildCommandResponseFrame(
            encPayload, encLen, sourceID, cmdOpts, txSequenceNumber);
        txSequenceNumber++;
        currentTxContext = TxContext::COMMAND_RESPONSE;
        resonantRadio.send(response.frame, response.size);
        delete[] response.frame;
        delete[] encPayload;
    } else {
        FrameData response = resonantFrame.buildCommandResponseFrame(
            responseData, 2, sourceID, cmdOpts, txSequenceNumber);
        txSequenceNumber++;
        currentTxContext = TxContext::COMMAND_RESPONSE;
        resonantRadio.send(response.frame, response.size);
        delete[] response.frame;
    }
    
    Serial1.printf("Command response sent: cmd=0x%02X, result=0x%02X\n", commandId, responseCode);
}

// ============================================================================
// Callback: Data Received (already validated by ResonantLRRadio)
// ============================================================================
void onDataReceived(ValidateFrameResult& result, uint8_t* data, size_t dataLength, int16_t rssi, int8_t snr)
{
    Serial1.println("\n=== Data Received ===");
    Serial1.printf("RSSI: %d dBm, SNR: %d dB\n", rssi, snr);
    Serial1.printf("Frame Type: 0x%02X, Options: 0x%02X\n", result.frameType, result.options);
    Serial1.printf("Data Length: %zu bytes\n", dataLength);
    
    if (result.frameType == resonantFrame.acknowledgementFrameType) {
        Serial1.println("ACK received!");
        storage.resetAckFailCount();
        powerManager.markRxComplete();
        if(firstBoot) {
            Serial1.println("First boot - sending metrics frame...");
            sendMetricsFrame();
        }else{
            powerManager.requestSleep();
        }
        
    } else if (result.frameType == resonantFrame.commandFrameType) {
        Serial1.println("Command frame received");

        // Attempt decryption; fall back to plaintext if encryption isn't active
        if (encryption.isInitialized() && dataLength > ENCRYPTION_OVERHEAD) {
            uint8_t plaintext[dataLength];
            size_t ptLen = 0;
            if (decryptPayload(data, dataLength, result.frameType,
                               result.sourceID, result.sequenceNumber, plaintext, &ptLen)) {
                Serial1.printf("Decrypted command payload: %zu bytes\n", ptLen);
                if (ptLen >= 1) {
                    handleCommand(plaintext[0], plaintext + 1, ptLen - 1, result.sourceID);
                } else {
                    Serial1.println("Error: Decrypted command has no data");
                }
            } else {
                Serial1.println("Decryption failed, treating as plaintext");
                if (dataLength >= 1) {
                    handleCommand(data[0], data + 1, dataLength - 1, result.sourceID);
                }
            }
        } else if (dataLength >= 1) {
            handleCommand(data[0], data + 1, dataLength - 1, result.sourceID);
        } else {
            Serial1.println("Error: Command frame has no data");
        }

    } else if (result.frameType == resonantFrame.adoptionRequestFrameType) {
        Serial1.println("Adoption request received!");
        Serial1.printf("Source ID: %02X:%02X:%02X:%02X\n",
            result.sourceID[0], result.sourceID[1], result.sourceID[2], result.sourceID[3]);

        // Spec payload: gateway_id(4) + ecdh_pubkey(64) + nonce(16) + ecdsa_sig(64) +
        //               tx_channel(1) + tx_interval(2) + cert_length(2) + gateway_der_cert(L)
        constexpr size_t MIN_ADOPTION_REQ_LEN = 4 + 64 + 16 + 64 + 1 + 2 + 2; // 153 bytes minimum

        if (encryption.isInitialized() && dataLength >= MIN_ADOPTION_REQ_LEN && data != nullptr) {
            size_t offset = 0;
            const uint8_t* gatewayId       = data + offset;  offset += 4;
            const uint8_t* gatewayPubKey   = data + offset;  offset += 64;
            const uint8_t* challengeNonce  = data + offset;  offset += 16;
            const uint8_t* gatewaySig      = data + offset;  offset += 64;
            uint8_t txChannel              = data[offset];    offset += 1;
            uint16_t txInterval            = ((uint16_t)data[offset] << 8) | data[offset + 1]; offset += 2;
            uint16_t certLength            = ((uint16_t)data[offset] << 8) | data[offset + 1]; offset += 2;

            Serial1.printf("Gateway ID: %02X:%02X:%02X:%02X\n",
                gatewayId[0], gatewayId[1], gatewayId[2], gatewayId[3]);
            Serial1.printf("TX Channel: %u, TX Interval: %u sec\n", txChannel, txInterval);

            const uint8_t* gatewayCert = nullptr;
            if (certLength > 0 && offset + certLength <= dataLength) {
                gatewayCert = data + offset;
            }

            // Step 4a: Verify gateway certificate chain
            bool certVerified = false;
            if (gatewayCert != nullptr && certLength > 0) {
                if (encryption.verifyCertChain(gatewayCert, certLength)) {
                    Serial1.println("Gateway certificate chain verified");
                    certVerified = true;
                } else {
                    Serial1.println("WARNING: Gateway certificate chain verification failed");
                }
            } else {
                Serial1.println("No gateway cert in payload, skipping chain verification");
            }

            // Step 4b: Extract gateway long-term public key from cert and verify ECDSA signature
            bool sigVerified = false;
            if (certVerified && gatewayCert != nullptr) {
                uint8_t gwLongTermPubKey[ResonantEncryption::P256_PUBKEY_SIZE];
                if (encryption.extractPubKeyFromCert(gatewayCert, certLength, gwLongTermPubKey)) {
                    // Verify signature over (gateway_ecdh_pubkey || challenge_nonce)
                    uint8_t signedData[64 + 16];
                    memcpy(signedData, gatewayPubKey, 64);
                    memcpy(signedData + 64, challengeNonce, 16);
                    if (encryption.verifySignature(gwLongTermPubKey, signedData, sizeof(signedData), gatewaySig)) {
                        Serial1.println("Gateway ECDSA signature verified");
                        sigVerified = true;
                    } else {
                        Serial1.println("WARNING: Gateway ECDSA signature verification failed");
                    }
                } else {
                    Serial1.println("WARNING: Failed to extract public key from gateway cert");
                }
            } else if (!certVerified && gatewayCert != nullptr) {
                Serial1.println("Skipping signature verification (cert not verified)");
            } else {
                // No cert -- fall back to trusting the ephemeral key directly (dev/testing)
                Serial1.println("No cert available, proceeding without attestation (dev mode)");
                sigVerified = true;
            }

            if (!sigVerified && gatewayCert != nullptr) {
                Serial1.println("Adoption rejected: mutual attestation failed");
                powerManager.markRxComplete();
                return;
            }

            // Step 5: ECDH + HKDF
            storage.setParentId(gatewayId);
            txSequenceNumber = 1;
            Serial1.println("Parent ID stored, sequence number reset");

            uint8_t sharedSecret[ResonantEncryption::SHARED_SECRET_SIZE];
            uint8_t sensorId[4];
            getDeviceSensorId(sensorId);

            if (encryption.performECDH(gatewayPubKey, sharedSecret)) {
                if (encryption.deriveSessionKey(sharedSecret, sensorId, 4,
                                                gatewayId, 4)) {
                    Serial1.println("Session key derived from adoption handshake");
                } else {
                    Serial1.println("WARNING: Session key derivation failed");
                }
                memset(sharedSecret, 0, sizeof(sharedSecret));
            } else {
                Serial1.println("WARNING: ECDH key agreement failed");
            }

            powerManager.markRxComplete();
            delay(150);
            uint8_t gwIdCopy[4];
            memcpy(gwIdCopy, gatewayId, 4);
            sendAdoptionAcceptCrypto(gwIdCopy, challengeNonce);
        } else {
            storage.setParentId(result.sourceID);
            txSequenceNumber = 1;
            Serial1.println("Parent ID stored (non-crypto adoption), sequence number reset");
            if (dataLength > 0 && data != nullptr) {
                Serial1.printf("Network config received: %zu bytes\n", dataLength);
            }
            powerManager.markRxComplete();
            delay(150);
            sendAdoptionAccept(result.sourceID);
        }

    } else if (result.frameType == resonantFrame.multiPacketFrameType) {
        Serial1.println("Multi-packet data received (fully reassembled)");
        Serial1.printf("Total packets: %d\n", result.totalPackets);
    } else {
        Serial1.println("Other frame type received");
    }
    
    Serial1.println("=====================\n");
}

// ============================================================================
// Callback: Transmission Complete
// ============================================================================
void onTxComplete(bool success, size_t bytesSent, uint8_t packetCount)
{
    // Note: markTxComplete() is now called by ResonantLRRadio when TX actually finishes
    unsigned long timeOnAir = powerManager.getTimeOnAir();
    
    Serial1.println("\n=== TX Complete ===");
    Serial1.printf("Success: %s\n", success ? "YES" : "NO");
    Serial1.printf("Bytes sent: %zu\n", bytesSent);
    Serial1.printf("Packets: %d\n", packetCount);
    Serial1.printf("Time on air: %lu ms\n", timeOnAir);
    
    if (packetCount > 1) {
        float throughput = (bytesSent * 1000.0f) / timeOnAir;
        Serial1.printf("Throughput: %.2f bytes/sec (%.2f KB/s)\n", throughput, throughput / 1024.0f);
    }
    Serial1.println("==================\n");

    transmissionComplete = true;

    switch (currentTxContext) {
        case TxContext::TELEMETRY:
            Serial1.println("Telemetry transmission complete");
            if(telemetryAckRequired) {
                Serial1.println("Telemetry ACK required, waiting for ACK...");
                Serial1.println("Waiting for ACK...");
                powerManager.markRxStart();
                resonantRadio.startRx(3000);  // 3 second timeout
            } else {
                if (firstBoot) {
                    Serial1.println("First boot - sending metrics frame...");
                    sendMetricsFrame();
                }else{
                    Serial1.println("Telemetry ACK not required, going to sleep...");
                    powerManager.requestSleep();
                }
            }
            break;
        case TxContext::METRICS:
            //We just transmitted Metrics so we stay awake and listen for commands  
            Serial1.println("Metrics transmission complete, staying awake and listening for commands...");
            powerManager.markRxStart();  
            resonantRadio.startRx(2000);
            break;
        case TxContext::COMMAND_RESPONSE:
            //Go to sleep
            powerManager.requestSleep();
            break;
        case TxContext::ACK:
            powerManager.requestSleep();
            break;
        case TxContext::ADOPTION_ADVERTISE:
            Serial1.println("Adoption advertise sent, listening for adoption request...");
            powerManager.markRxStart();
            resonantRadio.startRx(storage.getWaitAfterTx());
            break;
        case TxContext::ADOPTION_ACCEPT:
            Serial1.println("Adoption accept sent, going to sleep");
            powerManager.requestSleep();
            break;
        default:
            powerManager.requestSleep();
            break;
    }
}

// ============================================================================
// Callback: Radio Error
// ============================================================================
void onRadioError(uint8_t errorCode, const char* message)
{
    Serial1.printf("\n!!! Radio Error: [%d] %s !!!\n\n", errorCode, message);
    
    switch (errorCode) {
        case RADIO_ERROR_TX_TIMEOUT:
            powerManager.markRxComplete();
            powerManager.requestSleep();
            break;
        case RADIO_ERROR_RX_TIMEOUT:
            powerManager.markRxComplete();
            if (currentTxContext == TxContext::TELEMETRY && storage.isAdopted()) {
                storage.incrementAckFailCount();
                if (storage.isConnectionLost()) {
                    Serial1.println("Connection lost - clearing parent, will re-adopt next wake");
                    storage.clearParentId();
                }
            }
            powerManager.requestSleep();
            break;
        case RADIO_ERROR_RX_ACCUMULATION_TIMEOUT:
            Serial1.println("Multi-packet reception failed");
            break;
        default:
            break;
    }
}

// ============================================================================
// Background Tasks (runs on Core 0 - handles ALL radio operations)
// ============================================================================
void backgroundTasks(void *arg)
{
    Serial1.println("Radio task started on Core 0");
    
    // Initialize radio ON CORE 0 - this is critical for thread safety
    RadioConfig config = ResonantLRRadio::getLoRaLongRangePreset();
    Serial1.println("Using LoRa Long Range preset (SF7/BW125)");

    if (!resonantRadio.init(&resonantFrame, config)) {
        Serial1.println("ERROR: Radio initialization failed on Core 0!");
        // radioInitialized stays false, setup() will hang
        vTaskDelete(NULL);
        return;
    }
    
    Serial1.println("Radio init complete, starting main radio loop");
    
    // Main radio loop - processes requests, IRQs, and fires callbacks
    while(true) {
        resonantRadio.loop();  // Processes requests + IRQs + fires callbacks
        vTaskDelay(1); // 1ms delay for responsive radio handling
    }
}

void sendMetricsFrame(void)
{
    uint8_t data[9] = {0};
    uint8_t destinationID[4] = {0xFF, 0xFF, 0xFF, 0xFF};

    data[0] = FIRMWARE_VERSION;
    data[1] = HARDWARE_VERSION;
    data[2] = SENSOR_TYPE;
    float energyBuf = storage.getTotalEnergy();
    uint16_t energyBuffer_uint16 = (uint16_t)(energyBuf * 100);
    data[3] = (uint8_t)(energyBuffer_uint16 >> 8);
    data[4] = (uint8_t)(energyBuffer_uint16 & 0xFF);
    float batteryVoltage = powerManager.getBatteryVoltage();
    uint16_t batteryVoltage_uint16 = (uint16_t)(batteryVoltage * 100);
    data[5] = (uint8_t)(batteryVoltage_uint16 >> 8);
    data[6] = (uint8_t)(batteryVoltage_uint16 & 0xFF);
    data[7] = 0x00;
    data[8] = 0x00;

    uint8_t* encPayload = nullptr;
    size_t encLen = 0;

    uint8_t metricsOpts = ResonantFrame::buildOptionsV1(false);
    if (encryption.isInitialized() &&
        encryptPayload(data, 9, resonantFrame.metricsFrameType,
                       &encPayload, &encLen)) {
        FrameData metricsFrame = resonantFrame.buildMetricsFrame(
            encPayload, encLen, destinationID, metricsOpts, txSequenceNumber);
        txSequenceNumber++;
        currentTxContext = TxContext::METRICS;
        resonantRadio.send(metricsFrame.frame, metricsFrame.size);
        delete[] metricsFrame.frame;
        delete[] encPayload;
        Serial1.printf("Encrypted metrics frame sent (%zu bytes)\n", encLen);
    } else {
        FrameData metricsFrame = resonantFrame.buildMetricsFrame(data, 9, destinationID, metricsOpts, txSequenceNumber);
        txSequenceNumber++;
        currentTxContext = TxContext::METRICS;
        resonantRadio.send(metricsFrame.frame, metricsFrame.size);
        delete[] metricsFrame.frame;
    }
}

void sendAdoptionAdvertise(void)
{
    Serial1.println("Sending discovery/adoption advertise frame...");

    uint8_t deviceCert[ResonantEncryption::MAX_CERT_SIZE];
    size_t deviceCertLen = ResonantEncryption::MAX_CERT_SIZE;
    const uint8_t* certPtr = nullptr;
    size_t certLen = 0;

    if (encryption.isInitialized() && encryption.getDeviceCert(deviceCert, &deviceCertLen)) {
        certPtr = deviceCert;
        certLen = deviceCertLen;
        Serial1.printf("Including device cert (%zu bytes) in discovery\n", certLen);
    }

    uint8_t capabilities = 0x01;
    uint16_t txInterval = storage.getUInt16(StorageKeys::SLEEP_DURATION, 5);

    FrameData frame = resonantFrame.buildDiscoveryFrame(
        SENSOR_TYPE, HARDWARE_VERSION, FIRMWARE_VERSION,
        capabilities, txInterval, certPtr, certLen, txSequenceNumber);

    currentTxContext = TxContext::ADOPTION_ADVERTISE;
    uint8_t broadcastId[4] = {0xFF, 0xFF, 0xFF, 0xFF};
    resonantRadio.send(frame.frame, frame.size, broadcastId, false);
    delete[] frame.frame;
}

void sendAdoptionAccept(uint8_t destinationID[4])
{
    Serial1.printf("Sending adoption accept to %02X:%02X:%02X:%02X\n",
        destinationID[0], destinationID[1], destinationID[2], destinationID[3]);
    uint8_t acceptData[1] = {0xAA};
    uint8_t options = ResonantFrame::buildOptionsV1(false);
    FrameData frame = resonantFrame.buildAdoptionAcceptFrame(acceptData, 1, destinationID, options, txSequenceNumber);
    txSequenceNumber++;
    currentTxContext = TxContext::ADOPTION_ACCEPT;
    resonantRadio.send(frame.frame, frame.size);
    delete[] frame.frame;
}

void sendAdoptionAcceptCrypto(uint8_t destinationID[4], const uint8_t* challengeNonce)
{
    Serial1.printf("Sending crypto adoption accept to %02X:%02X:%02X:%02X\n",
        destinationID[0], destinationID[1], destinationID[2], destinationID[3]);

    uint8_t devicePubKey[ResonantEncryption::P256_PUBKEY_SIZE];
    if (!encryption.getPublicKey(devicePubKey)) {
        Serial1.println("getPublicKey failed, falling back to plain accept");
        sendAdoptionAccept(destinationID);
        return;
    }

    // Sign (devicePubKey || challengeNonce)
    uint8_t toSign[64 + 16];
    memcpy(toSign, devicePubKey, 64);
    memcpy(toSign + 64, challengeNonce, 16);

    uint8_t signature[ResonantEncryption::P256_SIG_SIZE];
    if (!encryption.signData(toSign, sizeof(toSign), signature)) {
        Serial1.println("signData failed, falling back to plain accept");
        sendAdoptionAccept(destinationID);
        return;
    }

    // Encrypt the challenge nonce as proof of key agreement (no AAD per spec)
    uint8_t encryptedNonce[16];
    uint8_t iv[ResonantEncryption::GCM_IV_SIZE];
    uint8_t tag[ResonantEncryption::GCM_TAG_SIZE];

    if (!encryption.encryptGCM(challengeNonce, 16, nullptr, 0,
                               encryptedNonce, iv, tag)) {
        Serial1.println("encryptGCM nonce proof failed, falling back to plain accept");
        sendAdoptionAccept(destinationID);
        return;
    }

    // Get device DER certificate
    uint8_t deviceCert[ResonantEncryption::MAX_CERT_SIZE];
    size_t deviceCertLen = ResonantEncryption::MAX_CERT_SIZE;
    bool hasCert = encryption.getDeviceCert(deviceCert, &deviceCertLen);
    if (!hasCert) {
        deviceCertLen = 0;
        Serial1.println("No device cert available, sending without cert");
    }

    // Spec payload: pubkey(64) + sig(64) + iv(12) + encNonce(16) + tag(16) + cert_len(2) + cert(L)
    size_t payloadSize = 64 + 64 + 12 + 16 + 16 + 2 + deviceCertLen;
    uint8_t* payload = new uint8_t[payloadSize];
    if (payload == nullptr) {
        Serial1.println("Payload allocation failed");
        sendAdoptionAccept(destinationID);
        return;
    }

    size_t offset = 0;
    memcpy(payload + offset, devicePubKey, 64);       offset += 64;
    memcpy(payload + offset, signature, 64);          offset += 64;
    memcpy(payload + offset, iv, 12);                 offset += 12;
    memcpy(payload + offset, encryptedNonce, 16);     offset += 16;
    memcpy(payload + offset, tag, 16);                offset += 16;
    payload[offset] = (deviceCertLen >> 8) & 0xFF;    offset += 1;
    payload[offset] = deviceCertLen & 0xFF;           offset += 1;
    if (deviceCertLen > 0) {
        memcpy(payload + offset, deviceCert, deviceCertLen);
    }

    uint8_t options = ResonantFrame::buildOptionsV1(false);

    FrameData frame = resonantFrame.buildAdoptionAcceptFrame(
        payload, payloadSize, destinationID, options, txSequenceNumber);
    txSequenceNumber++;
    currentTxContext = TxContext::ADOPTION_ACCEPT;
    resonantRadio.send(frame.frame, frame.size, destinationID, false);
    delete[] frame.frame;

    delete[] payload;
    Serial1.printf("Crypto adoption accept sent (%zu bytes: pubkey + sig + nonce proof + cert)\n", payloadSize);
}

// ============================================================================
// Encryption Helpers
// ============================================================================

void getDeviceSensorId(uint8_t* sensorId)
{
    uint8_t mac[6];
    esp_efuse_mac_get_default(mac);
    memcpy(sensorId, mac + 2, 4);
}

void buildAAD(uint8_t* aad, uint8_t frameType, const uint8_t* id, uint32_t seqNum)
{
    aad[0] = frameType;
    memcpy(aad + 1, id, 4);
    aad[5] = (seqNum >> 24) & 0xFF;
    aad[6] = (seqNum >> 16) & 0xFF;
    aad[7] = (seqNum >> 8)  & 0xFF;
    aad[8] = seqNum & 0xFF;
}

bool encryptPayload(const uint8_t* plaintext, size_t plaintextLen,
                    uint8_t frameType, uint8_t** outPayload, size_t* outLen)
{
    if (!encryption.isInitialized() || plaintext == nullptr || outPayload == nullptr) {
        return false;
    }

    uint8_t sensorId[4];
    getDeviceSensorId(sensorId);

    uint8_t aad[9];
    buildAAD(aad, frameType, sensorId, txSequenceNumber);

    uint8_t ciphertext[plaintextLen];
    uint8_t iv[ResonantEncryption::GCM_IV_SIZE];
    uint8_t tag[ResonantEncryption::GCM_TAG_SIZE];

    if (!encryption.encryptGCM(plaintext, plaintextLen, aad, sizeof(aad),
                               ciphertext, iv, tag)) {
        return false;
    }

    // Pack: iv(12) + ciphertext(N) + tag(16)
    *outLen = ResonantEncryption::GCM_IV_SIZE + plaintextLen
            + ResonantEncryption::GCM_TAG_SIZE;
    *outPayload = new uint8_t[*outLen];
    if (*outPayload == nullptr) {
        return false;
    }

    memcpy(*outPayload, iv, ResonantEncryption::GCM_IV_SIZE);
    memcpy(*outPayload + ResonantEncryption::GCM_IV_SIZE, ciphertext, plaintextLen);
    memcpy(*outPayload + ResonantEncryption::GCM_IV_SIZE + plaintextLen,
           tag, ResonantEncryption::GCM_TAG_SIZE);

    Serial1.printf("Payload encrypted: %zu -> %zu bytes (seq=%u)\n",
                   plaintextLen, *outLen, txSequenceNumber);
    return true;
}

bool decryptPayload(const uint8_t* encPayload, size_t encPayloadLen,
                    uint8_t frameType, const uint8_t* senderId,
                    uint32_t sequenceNumber,
                    uint8_t* plaintext, size_t* plaintextLen)
{
    if (!encryption.isInitialized() || encPayload == nullptr ||
        plaintext == nullptr || plaintextLen == nullptr) {
        return false;
    }

    if (encPayloadLen < ENCRYPTION_OVERHEAD) {
        Serial1.println("Encrypted payload too short");
        return false;
    }

    const uint8_t* iv = encPayload;
    size_t ctLen = encPayloadLen - ResonantEncryption::GCM_IV_SIZE
                 - ResonantEncryption::GCM_TAG_SIZE;
    const uint8_t* ciphertext = encPayload + ResonantEncryption::GCM_IV_SIZE;
    const uint8_t* tag = encPayload + ResonantEncryption::GCM_IV_SIZE + ctLen;

    uint8_t aad[9];
    buildAAD(aad, frameType, senderId, sequenceNumber);

    bool tagVerified = false;
    if (!encryption.decryptGCM(ciphertext, ctLen, aad, sizeof(aad),
                               iv, tag, plaintext, &tagVerified)) {
        return false;
    }

    if (!tagVerified) {
        Serial1.println("GCM tag verification failed -- possible tampering");
        return false;
    }

    *plaintextLen = ctLen;
    return true;
}